font_family      Inconsolata Nerd Font Regular
bold_font        Inconsolata Nerd Font Bold
italic_font      Inconsolata Nerd Font Italic
bold_italic_font Inconsolata Nerd Font Bold Italic
font_size 14

scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_lines 10000

cursor_blink_interval 0

map ctrl+shift+b scroll_page_up
map ctrl+shift+f scroll_page_down

# +-------+
# | THEME |
# +-------+
include current_theme.conf
