#!/usr/bin/env bash

# Source colors
install_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" &> /dev/null && pwd)"
source "$install_dir/colors"

function prompt_ask {
  local answer ret_val

  while true; do
    printf >&2 '%s ' 'Do you wish to continue? (y/n): '
    read -r answer

    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && ret_val=0
      [[ $answer = [Nn] ]] && ret_val=1
      break
    fi
  done

  return "$ret_val"
}

has_cmd() {
  local opt

  for opt in "$@"; do
    if ! command -v "$opt" >/dev/null 2>&1; then
      return 1
    fi
  done
  return 0
}


# Check whether a string represents "true" (1, y, yes, t, true, o, on).
is_true() {
  local val
  val=${1:-0}
  val=$(echo "$val" | tr '[:upper:]' '[:lower:]')

  case $val in
    1) return 0;;
    t|true) return 0;;
    y|yes) return 0;;
    o|on) return 0;;
    *) return 1;;
  esac
}

do_action_in_dir() {
  local dir ret_val
  dir="$1"
  ret_val=0
  shift

  if cd "$dir" >/dev/null 2>&1; then
    if ! "$@"; then
      ret_val=1
    fi

    cd - >/dev/null 2>&1 || ret_val=1
  else
    ret_val=1
  fi

  return "$ret_val"
}

remove_broken_symlinks() {
  find "$1" -maxdepth 1 -xtype l -delete
}

extract_file() {
  local ret_val file file_lower full_path stripped_name
  ret_val=0
  file="$1"
  file_lower=$(echo "$file" | tr '[:upper:]' '[:lower:]')
  full_path="$(readlink -f "$file" 2>/dev/null || echo "$file")"

  if [[ ! -f $full_path ]]; then
    error "'$file' is not a valid file"
    return 1
  fi

  case $file_lower in
    (*.tar.gz|*.tgz)
      if has_cmd pigz; then
        tar -I pigz -xvf "$full_path"
      else
        tar zxvf "$full_path"
      fi ;;
    (*.tar.bz2|*.tbz|*.tbz2)
      if has_cmd pbzip2; then
        tar -I pbzip2 -xvf "$full_path"
      else
        tar xvjf "$full_path"
      fi ;;
    (*.tar.xz|*.txz)
      if has_cmd pixz; then
        tar -I pixz -xvf "$full_path"
      else
        if tar --xz -tf &>/dev/null; then
          tar --xz -xvf "$full_path"
        else
          xzcat "$full_path" | tar xvf -
        fi
      fi ;;
    (*.tar.zma|*.tlz)
      if tar --lzma -tf &>/dev/null; then
        tar --lzma -xvf "$full_path"
      else
        lzcat "$full_path" | tar xvf -
      fi ;;
    (*.tar.zst|*.tzst)
      if tar --zstd -tf &>/dev/null; then
        tar --zstd -xvf "$full_path"
      else
        zstdcat "$full_path" | tar xvf -
      fi ;;
    (*.tar) tar xvf "$full_path" ;;
    (*.tar.lz) has_cmd lzip && tar xvf "$full_path" ;;
    (*.tar.lz4) lz4 -c -d "$full_path" | tar xvf - ;;
    (*.tar.lrz) has_cmd lrzuntar && lrzuntar "$full_path" ;;
    (*.gz)
      stripped_name=$(basename "$file")
      stripped_name=${stripped_name%.*}

      if has_cmd pigz; then
        pigz -cdk "$full_path" > "$stripped_name"
      else
        gunzip -ck "$full_path" > "$stripped_name"
      fi ;;
    (*.bz2)
      if has_cmd pbzip2; then
        pbzip2 -d "$full_path"
      else
        bunzip2 "$full_path"
      fi ;;
    (*.xz) unxz "$full_path" ;;
    (*.lrz) has_cmd lrunzip && lrunzip "$full_path" ;;
    (*.lz4) lz4 -d "$full_path" ;;
    (*.lzma) unlzma "$full_path" ;;
    (*.z) uncompress "$full_path" ;;
    (*.zip|*.war|*.jar|*.ear|*.sublime-package|*.ipa|*.ipsw|*.xpi|*.apk|*.aar|*.whl|*.vsix|*.crx|*.pk3|*.pk4) unzip "$full_path" ;;
    (*.rar)
      if has_cmd unrar; then
        unrar x -ad "$full_path"
      elif has_cmd unar; then
        unar -o . "$full_path"
      else
        warning "Cannot extract RAR files: install unrar or unar" >&2
        ret_val=1
      fi ;;
    (*.rpm) rpm2cpio "$full_path" | cpio --quiet -id ;;
    (*.7z | *.7z.[0-9]* | *.pk7) 7za x "$full_path" ;;
    (*.deb)
      if has_cmd dpkg-debz; then
        dpkg-deb -R "$full_path" .
      else
        ar vx "$full_path"
        mkdir -p "control" "data"
        do_action_in_dir "control" find .. -type f -name 'control.tar.*' -exec extract -r {} \;
        do_action_in_dir "data" find .. -type f -name 'data.tar.*' -exec extract -r {} \;
        command rm debian-binary
      fi ;;
    (*.zst)
      stripped_name=$(basename "$file")
      stripped_name=${stripped_name%.*}
      unzstd --stdout "$full_path" > "$stripped_name" ;;
    (*.cab|*.exe) cabextract "$full_path" ;;
    (*.cpio|*.obscpio) cpio -idmvF "$full_path" ;;
    (*.zpaq) zpaq x "$full_path" ;;
    (*.zlib)
      stripped_name=${file%.*}
      zlib-flate -uncompress < "$full_path" > "$stripped_name" ;;
    (*)
        warning "'$file' cannot be extracted"
        ret_val=1 ;;
  esac

  (( ret_val = ret_val > 0 ? ret_val : $? ))
  return "$ret_val"
}

mes_color() {
  local color=$1
  local msg=$2

  printf "%b%s%b\n" "$color" "$msg" "$NC"
}

mes_nc() {
  mes_color "$NC" "$1"
}

error() {
  local msg="ERROR: $1"
  mes_color "$RED" "$msg" >&2
  return 1
}

warning() {
  local msg="WARNING: $1"
  mes_color "$YELLOW" "$msg"
}

warning_severe() {
  local msg="WARNING: $1"
  mes_color "$LIGHT_RED" "$msg"
}

info() {
  mes_color "$CYAN" "$1"
}

success() {
  mes_color "$GREEN" "$1"
}

mes_update() {
  local msg="--> Updating $1"
  mes_color "$YELLOW" "$msg"
}

dot_install() {
  printf "%b--> Installing %b%s %bconfig %b\n" "$BLUE" "$YELLOW" "$1" "$BLUE" "$NC"
  local file="$DOTFILES/install/install-$1.sh"

  if [[ -f $file ]]; then
    "$file"
  else
    error "Found no install file with name $1"
  fi
}
