#!/usr/bin/env bash

# Git user and email to set up git automatically
#export GIT_USER=""
#export GIT_EMAIL=""

# Packages to install for Debian/Ubuntu
export PACKAGES_APT=(
  "build-essential"
  "chafa"
  "curl"
  "dnsutils"
  "fastfetch"
  "file"
  "fontconfig"
  "gnupg"
  "libimage-exiftool-perl"
  "libreadline-dev"
  "procps"
  "unzip"
  "wget"
  "xdg-user-dirs"
  "xz-utils"
  "zip"
  "zsh"
)

export PACKAGES_PACMAN=(
  "base"
  "base-devel"
  "bind"
  "chafa"
  "curl"
  "fastfetch"
  "file"
  "fontconfig"
  "gnupg"
  "less"
  "man-db"
  "man-pages"
  "pacman-contrib"
  "perl-image-exiftool"
  "procps-ng"
  "readline"
  "unzip"
  "wget"
  "xdg-user-dirst"
  "xz"
  "zip"
  "zsh"
)
