#!/usr/bin/env bash

# Git user and email to set up git automatically
#export GIT_USER=""
#export GIT_EMAIL=""

# Packages to install for Debian/Ubuntu
export PACKAGES_APT=(
  "build-essential"
  "chafa"
  "curl"
  "dnsutils"
  "fastfetch"
  "file"
  "fontconfig"
  "gnupg"
  "gsettings-desktop-schemas"
  "libglib2.0-0t64"
  "libglib2.0-data"
  "libglib2.0-bin"
  "libimage-exiftool-perl"
  "libreadline-dev"
  "man-db"
  "manpages"
  "procps"
  "unzip"
  "wget"
  "xdg-user-dirs"
  "xz-utils"
  "zip"
  "zsh"
)

# Packages to install for Arch
export PACKAGES_PACMAN=(
  "base"
  "base-devel"
  "bind"
  "chafa"
  "curl"
  "fastfetch"
  "file"
  "fontconfig"
  "glib2"
  "gnupg"
  "gsettings-desktop-schemas"
  "less"
  "man-db"
  "man-pages"
  "pacman-contrib"
  "perl-image-exiftool"
  "procps-ng"
  "readline"
  "unzip"
  "wget"
  "xdg-user-dirs"
  "xz"
  "zip"
  "zsh"
)

# Packages to install for Fedora/RHEL/Alma. EPEL repository must be enabled
export PACKAGES_DNF=(
  "bind-utils"
  "chafa"
  "curl"
  "fastfetch"
  "file"
  "fontconfig"
  "glib2"
  "gnupg2"
  "gsettings-desktop-schemas"
  "less"
  "man-db"
  "man-pages"
  "perl-Image-ExifTool"
  "procps-ng"
  "readline-devel"
  "unzip"
  "wget"
  "xdg-user-dirs"
  "xz"
  "zip"
  "zsh"
)

# Group packages to install for Fedora/RHEL/Alma
export GROUP_PACKAGES_DNF=(
  "Development Tools"
)