#!/usr/bin/env bash

alias bigf='find / -xdev -type f -size +500M'  # display "big" files > 500M

# +-----+
# | X11 |
# +-----+
alias xclass='xprop | grep WM_CLASS' # display xprop class

# +------+
# | wget |
# +------+
alias wget='wget --hsts-file=$XDG_DATA_HOME/wget-hsts'

# +----+
# | cp |
# +----+
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

# +------+
# | grep |
# +------+
alias grep="grep -P -i --color=auto"

# +--------+
# | pbcopy |
# +--------+
if ! command -v pbcopy >/dev/null 2>&1; then
  if [[ "$OSTYPE" == cygwin* ]]; then
    alias pbcopy='tee > /dev/clipboard'
    alias pbpaste='cat /dev/clipboard'
  elif [[ "$OSTYPE" == linux-android ]]; then
    alias pbcopy='termux-clipboard-set'
    alias pbpaste='termux-clipboard-get'
  elif command -v wl-copy >/dev/null 2>&1 && command -v wl-paste >/dev/null 2>&1; then
    alias pbcopy='wl-copy'
    alias pbpaste='wl-paste'
  elif [[ -n $DISPLAY ]]; then
    if command -v xclip >/dev/null 2>&1; then
      alias pbcopy='xclip -selection clipboard -in'
      alias pbpaste='xclip -selection clipboard -out'
    elif command -v xsel >/dev/null 2>&1; then
      alias pbcopy='xsel --clipboard --input'
      alias pbpaste='xsel --clipboard --output'
    fi
  fi
fi

# +------+
# | dust |
# +------+
alias dust='du -sh * | sort -hr'

# +------+
# | ping |
# +------+
alias pg='ping 8.8.8.8'

# +------+
# | time |
# +------+
alias time='/usr/bin/time'

# +----+
# | bc |
# +----+
alias calc="noglob calcul"

# +-----+
# | bat |
# +-----+
alias batl='bat --paging=never -l log'

# +---------+
# | netstat |
# +---------+
alias port="netstat -tulpn | grep"

# +--------+
# | Neovim |
# +--------+
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim="vim -u /usr/share/nvim/archlinux.vim" # nvim with default config
alias nvimc='rm -I $VIMCONFIG/swap/*'             # clean nvim swap file
alias nvimcu='rm -I $VIMCONFIG/undo/*'            # clean the vim undo
alias nvimd='nvim --noplugin -u NONE'             # launch nvim without any plugin or config (nvim debug)
alias lvim='\vim -c "set nowrap|syntax off"'        # fast vim for big files / big oneliner

# +------+
# | tmux |
# +------+
alias tmuxk='tmux kill-session -t'
alias tmuxa='tmux attach -t'
alias tmuxl='tmux list-sessions'


# +-------+
# | tmuxp |
# +-------+
alias mux='tmuxp load'

# +--------+
# | docker |
# +--------+
alias dockls="docker container ls | awk 'NR > 1 {print \$NF}'"                  # display names of running containers
alias dockRr='docker rm $(docker ps -a -q)'                                     # delete every containers / images
alias dockRr='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
alias dockimg='docker images'                                                   # list images installed
alias dockprune='docker system prune -a'                                        # prune everything
alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
alias dockce='docker-compose run --rm'

# +----------------+
# | docker-compose |
# +----------------+
alias docker-compose-dev='docker-compose -f docker-compose-dev.yml' # run a different config file than the default one


# +--------+
# | podman |
# +--------+
if ! command -v podman >/dev/null 2>&1; then
  if command -v podman-remote >/dev/null 2>&1; then
    alias podman='podman-remote'
  fi
else
  if ! command -v podman-remote >/dev/null 2>&1; then
    alias -remote='podman --remote'
  fi
fi

# +---------+
# | folders |
# +---------+
alias home='cd $HOME/'
alias work='cd $HOME/workspace'
alias doc='cd $HOME/Documents'
alias dow='cd $HOME/Downloads'
alias dot='cd $HOME/.dotfiles'

# +-------+
# | print |
# +-------+
alias print-fpath='echo $FPATH | tr ":" "\n"'
alias print-path='echo $PATH | tr ":" "\n"'
alias print-functions='print -l ${(k)functions[(I)[^_]*]} | sort'

# +--------+
# | commit |
# +--------+
if command -v flatpak >/dev/null 2>&1; then
  if flatpak info re.sonny.Commit >/dev/null 2>&1; then
    alias commit='flatpak run re.sonny.Commit'
  else
    alias commit='$EDITOR'
  fi
else
  alias commit='$EDITOR'
fi

# +-------+
# | maven |
# +-------+
source "$DOTFILES/aliases/mvn"
