#!/usr/bin/env zsh

NC="\033[0m"
BOLD="\033[1m"
BLACK="\033[30m"
RED="\033[0;31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[97m"

if ! command -v fzf >/dev/null 2>&1; then
  printf "%b%s%b\n" "$RED" "Fzf is not installed" "$NC"
  return 1
fi

if ! command -v flatpak >/dev/null 2>&1; then
  printf "%b%s%b\n" "$RED" "Flatpak is not installed" "$NC"
  return 1
fi

AWK_VAR="awk -v BLK=${BLACK} -v RED=${RED} -v GRN=${GREEN} -v YLW=${YELLOW} -v BLU=${BLUE} -v MGN=${MAGENTA} -v CYN=${CYAN} -v WHT=${WHITE} -v BLD=${BOLD} -v RST=${NC}"

# Searches only from flathub repository
flatpak remote-ls --user flathub --cached --columns=app,name,description \
  | awk -v cyn="${CYAN}" -v blu="${BLUE}" -v bld="${BOLD}" -v res="${NC}" \
  '{
    app_info="";
    for(i=2;i<=NF;i++){
      app_info=cyn app_info" "$i
    };
    print blu bld $2" -" res app_info "|" $1
    }' \
  | column -t -s "|" -R0 \
  | fzf \
    --ansi \
    --with-nth=1.. \
    --prompt="Install > " \
    --preview-window "nohidden,40%,<50(down,50%,border-rounded)" \
    --preview "flatpak --user remote-info flathub {-1} | $AWK_VAR -F\":\" '{print YLW BLD \$1 RST WHT \$2}'" \
    --bind "enter:execute(flatpak install --user flathub {-1})"
zle reset-prompt
