#!/usr/bin/env zsh

function _podman {
  if (( $+commands[podman] )); then
    command podman "$@"
    return $?
  fi

  if (( $+commands[podman-remote] )); then
    command podman-remote "$@"
    return $?
  fi

  echo "podman command not found" >&2
  return 1
}

_podman "$@"