#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

source "$DOTFILES/bootstrap"

CURRENT_DIR=$(pwd)
XDG_DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)
is_temp=0
is_pipe=1
is_silent=0
file_name=""
download_dir=""
url=""

_usage() {
  cat <<\EOF
  Utility program to download files, 'download' will use curl as primary tool and use wget if curl is not installed.
  By default 'download' will read the <url> to "Standard Output", unless the '-o' flag is used.

  Usage: download [options...] <url>
  -h, --help                  - Shows this text
  -s, --silent                - Silent mode
  -o, --output                - Writes the output to a file
  -f, --file=<file>           - Name of the file to write to (default is 'basename <url>')
  -d, --directory=<directory> - Directory the file is downloaded to (Default is $XDG_DOWNLOAD_DIR. If $XDG_DOWNLOAD_DIR is not set, then current directory is used)
  -t, --temp                  - The downloaded file will be saved to tmp-folder
EOF
}

# Attempt to make all curl commands more resilient to failure. The speed
# flags help protect against zombie connections while still allowing long
# downloads on slower connections (avoiding --max-time).
_curl() {
  local args
  args=(
    "--fail"
    "--location"
    "--connect-timeout" "10"
    "--retry" "4"
    "--retry-connrefused"
    "--speed-limit" "100"
    "--speed-time" "30"
  )
  is_true "$is_silent" && args+=("--silent")
  args+=("${@}")

  curl "${args[@]}"
}

_wget() {
  local args
  args=(
    "--timeout=10"
    "--read-timeout=10"
    "--tries=4"
    "--retry-connrefused"
  )
  is_true "$is_silent" && args+=("--quiet")
  args+=("${@}")

  wget "${args[@]}"
}

_fetch() {
  if has_cmd curl; then
    _curl -o "$2" "$1"
  elif has_cmd wget; then
    _wget -O "$2" "$1"
  else
    error "Install curl or wget to download files"
    exit 1
  fi
}

_pipe() {
  if has_cmd curl; then
    _curl --silent --show-error "$1"
  elif has_cmd wget; then
    _wget -nv -O- "$1"
  else
    error "Install curl or wget to download files"
    exit 1
  fi
}

_get_temp_dir() {
  local tmp_file tmp_dir
  tmp_file=$(mktemp)
  tmp_dir=$(dirname "$tmp_file")
  rm -f "$tmp_file"

  echo "$tmp_dir"
}

_find_download_dir() {
  # Directory priority:
  # 1. Tmp-dir, if is_temp is true
  # 2. Input argument
  # 3. XDG_DOWNLOAD_DIR
  # 4. Current dir
  local default_download_dir=${XDG_DOWNLOAD_DIR:-$CURRENT_DIR}

  if is_true "$is_temp"; then
    local tmp_dir
    tmp_dir=$(_get_temp_dir)
    download_dir="$tmp_dir"
  else
    if [ -n "$download_dir" ]; then
      if [ "$download_dir" =  "." ]; then
        download_dir="$CURRENT_DIR"
      elif [ ! -d "$download_dir" ]; then
        download_dir="$default_download_dir"
      fi
    else
      download_dir="$default_download_dir"
    fi
  fi
}

_parse_args() {
  if [ $# -eq 0 ]; then
    _usage
    exit 0
  fi

  local i
  for i in "$@"; do
    case $i in
      -h|--help)
        _usage
        exit 0
        ;;
      -o|--output)
        is_pipe=0
        shift
        ;;
      -s|--silent)
        is_silent=1
        shift
        ;;
      -f=*|--file=*)
        file_name="${i#*=}"
        is_pipe=0
        shift
        ;;
      -d=*|--directory=*)
        download_dir="${i#*=}"
        is_pipe=0
        shift
        ;;
      -t|--temp)
        is_temp=1
        is_pipe=0
        shift
        ;;
      -*)
        error "Unknown option: '$1'"
        ;;
      *)
        ;;
    esac
  done

  if [ $# -ne 1 ]; then
    error "Wrong input"
  fi

  url=$1
  if [[ -z $url ]]; then
    error "URL not provided"
  fi

  file_name=${file_name:-$(basename "$url")}
}

_parse_args "$@"

if is_true "$is_pipe"; then
  if ! _pipe "$url"; then
    error "URL did not respond successfully, retry or check your connection: $url"
    exit 1
  fi
else
  _find_download_dir
  file_path="$download_dir/$file_name"

  if ! _fetch "$url" "$file_path"; then
    error "URL did not respond successfully, retry or check your connection: $url"
    exit 1
  fi

  echo "$file_path"
fi
