#!/usr/bin/env bash
source "$DOTFILES/colors"

set -o errexit
set -o pipefail

script_name=$(basename "$0")
readonly script_name

if ! command -v fzf >/dev/null 2>&1; then
  printf "%b%s%b\n" "$RED" "Fzf is not installed" "$NC"
  exit 64
fi
if ! command -v dnf >/dev/null 2>&1; then
  printf "%b%s%b\n" "$RED" "Dnf is not installed" "$NC"
  exit 64
fi

preview_fun() {
  local pkg_name
  pkg_name=$(echo "$1" | awk '{print $1}')
  dnf --cacheonly --quiet --color=always info "$pkg_name"
}
export -f preview_fun

#Colors
declare -r esc=$'\033'
declare -r BLUE="${esc}[1m${esc}[34m"
declare -r RED="${esc}[31m"
declare -r GREEN="${esc}[32m"
declare -r YELLOW="${esc}[33m"
declare -r CYAN="${esc}[36m"
# Base commands
declare -r QRY="dnf --cacheonly --quiet repoquery "
declare -r PRVW="dnf --cacheonly --quiet --color=always info"
declare -r QRY_PRFX='  '
declare -r QRY_SFFX=' > '
# Install mode
declare -r INS_QRYS="${QRY} --qf '${CYAN}%{name}'"
declare -r INS_PRVW="${PRVW}"
declare -r INS_PRMPT="${CYAN}${QRY_PRFX}Install packages${QRY_SFFX}"
# Remove mode
declare -r RMV_QRYS="${QRY} --installed --qf '${RED}%{name}'"
declare -r RMV_PRVW="${PRVW} --installed"
declare -r RMV_PRMPT="${RED}${QRY_PRFX}Remove packages${QRY_SFFX}"
# Remove-userinstalled mode
declare -r RUI_QRYS="${QRY} --userinstalled --qf '${YELLOW}%{name}'"
declare -r RUI_PRVW="${PRVW} --installed"
declare -r RUI_PRMPT="${YELLOW}${QRY_PRFX}Remove User-Installed${QRY_SFFX}"
# Updates mode
declare -r UPD_QRY="${QRY} --upgrades --qf '${GREEN}%{name}'"
declare -r UPD_QRYS="if [[ $(${UPD_QRY} | wc -c) -ne 0 ]]; then ${UPD_QRY}; else echo ${GREEN}No updates available.; echo Try refreshing metadata cache...; fi"
declare -r UPD_PRVW="${PRVW}"
declare -r UPD_PRMPT="${GREEN}${QRY_PRFX}Upgrade packages${QRY_SFFX}"

mapfile -d '' fhelp <<-EOF

        "${script_name}"
        Interactive package manager for Fedora

        Alt-i       Install mode (default)
        Alt-r       Remove mode
        Alt-e       Remove User-Installed mode
        Alt-u       Updates mode
        Alt-m       Update package metadata cache

        Enter       Confirm selection
        Tab         Mark package ()
        Shift-Tab   Unmark package
        Ctrl-a      Select all

        ?           Help (this page)
        ESC         Quit
EOF

declare tmp_file
if tmp_file="$(mktemp --tmpdir "${script_name}".XXXXXX)"; then
  printf 'in' > "${tmp_file}" &&
  SHELL='/bin/bash' \
  FZF_DEFAULT_COMMAND="${INS_QRYS}" \
  fzf \
    --ansi \
	--multi \
	--query="$*" \
	--header=" ${script_name} | Press Alt+h for help or ESC to quit" \
	--header-first \
	--prompt="${INS_PRMPT}" \
	--marker=' ' \
	--preview-window='right,67%,wrap' \
	--preview="bash -c 'preview_fun {1}'" \
	--bind="enter:execute(if grep -q 'in' \"${tmp_file}\"; then sudo dnf install {+};
        elif grep -q 'rm' \"${tmp_file}\"; then sudo dnf remove {+}; \
        elif grep -q 'up' \"${tmp_file}\"; then sudo dnf upgrade {+}; fi; \
        read -s -r -n1 -p $'\n${BLUE}Press any key to continue...' && printf '\n')" \
	--bind="alt-i:unbind(alt-i)+reload(${INS_QRYS})+change-preview(${INS_PRVW} {1})+change-prompt(${INS_PRMPT})+execute-silent(printf 'in' > \"${tmp_file}\")+first+rebind(alt-r,alt-e,alt-u)" \
	--bind="alt-r:unbind(alt-r)+reload(${RMV_QRYS})+change-preview(${RMV_PRVW} {1})+change-prompt(${RMV_PRMPT})+execute-silent(printf 'rm' > \"${tmp_file}\")+first+rebind(alt-i,alt-e,alt-u)" \
	--bind="alt-e:unbind(alt-e)+reload(${RUI_QRYS})+change-preview(${RUI_PRVW} {1})+change-prompt(${RUI_PRMPT})+execute-silent(printf 'rm' > \"${tmp_file}\")+first+rebind(alt-i,alt-r,alt-u)" \
	--bind="alt-u:unbind(alt-u)+reload(${UPD_QRYS})+change-preview(${UPD_PRVW} {1})+change-prompt(${UPD_PRMPT})+execute-silent(printf 'up' > \"${tmp_file}\")+first+rebind(alt-i,alt-r,alt-e)" \
	--bind="alt-m:execute(sudo dnf makecache;read -s -r -n1 -p $'\n${BLUE}Press any key to continue...' && printf '\n')" \
	--bind="alt-h:preview(printf \"${fhelp[0]}\")" \
	--bind="ctrl-a:select-all"

  rm -f "${tmp_file}" &> /dev/null
else
  printf 'Error: Failed to create tmp file. $TMPDIR (or /tmp if $TMPDIR is unset) may not be writable.\n' >&2
  exit 65
fi
