#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

source "$DOTFILES/bootstrap"

packages_auto_confirm=0
manager=""
confirm_flag=""
packages=()

_usage() {
  cat <<\EOF
  Utility program to install packages. The following package managers are supported:
  - pacman
  - yay
  - apt
  - dnf
  - flatpak
  - snap
  - brew
  - brew-cask
  - mise

  Usage: install_package [options...] <packages>
  -h, --help               - Shows this text
  -m, --manager=<manager>  - The manager used to install packages; apt, pacman, yay etc.
  -y, --yes                - Install packages without confirmation
EOF
}

_parse_args() {
  if [ $# -eq 0 ]; then
    _usage
    exit 0
  fi

  local i
  for i in "$@"; do
    case $i in
      -h|--help)
        _usage
        exit 0 ;;
      -m=*|--manager=*)
        manager="${i#*=}"
        shift ;;
      -y|--yes)
        packages_auto_confirm=1
        shift ;;
      -*) error "Unknown option: '$1'" ;;
      *)
        packages+=("$1")
        shift ;;
    esac
  done

  if [ ${#packages[@]} -eq 0 ]; then
    error "No packages provided"
  fi
}

_parse_args "$@"

if is_true "$packages_auto_confirm"; then
  case $manager in
    pacman) confirm_flag="--noconfirm" ;;
    yay) confirm_flag="--noconfirm --answerdiff None --answerclean None" ;;
    apt) confirm_flag="--yes" ;;
    dnf|dnf-group|flatpak) confirm_flag="--assumeyes" ;;
  esac
fi

_install_pacman() {
  sudo pacman -Syu
  local pkg
  for pkg in "${packages[@]}"; do
    sudo pacman -S "$confirm_flag" --needed "$pkg"
  done
}

_install_yay() {
  yay -Syu
  local pkg
  for pkg in "${packages[@]}"; do
    yay -S "$confirm_flag" --needed "$pkg"
  done
}

_install_apt() {
  sudo apt update
  local pkg
  for pkg in "${packages[@]}"; do
    sudo apt install "$confirm_flag" "$pkg"
  done
}

_install_dnf() {
  local is_group pkg
  is_group=$1

  for pkg in "${packages[@]}"; do
    if is_true "$is_group"; then
      sudo dnf group install "$confirm_flag" "$pkg"
    else
      sudo dnf install "$confirm_flag" "$pkg"
    fi
  done
}

_install_flatpak() {
  flatpak update --user --appstream
  local pkg
  for pkg in "${packages[@]}"; do
    flatpak install flathub --user "$confirm_flag" "$pkg"
  done
}

_install_snap() {
  local pkg
  for pkg in "${packages[@]}"; do
    sudo snap install "$pkg"
  done
}

_install_brew() {
  local is_cask brew_opt pkg
  is_cask=$1
  brew_opt=""
  is_true "$is_cask" && brew_opt="--cask"

  HOMEBREW_NO_ASK=$packages_auto_confirm brew update
  for pkg in "${packages[@]}"; do
    HOMEBREW_NO_ASK=$packages_auto_confirm brew install "$brew_opt" "$pkg"
  done
}

_install_mise() {
  local pkg
  for pkg in "${packages[@]}"; do
    mise use -g "$pkg"
  done
}

case $manager in
  pacman) _install_pacman ;;
  yay) _install_yay ;;
  apt) _install_apt ;;
  dnf) _install_dnf 0 ;;
  dnf-group) _install_dnf 1 ;;
  flatpak) _install_flatpak ;;
  snap) _install_snap ;;
  brew) _install_brew 0 ;;
  brew-cask) _install_brew 1 ;;
  mise) _install_mise ;;
  *) error "Unknown package manager: '$manager'" ;;
esac