#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

source "$DOTFILES/bootstrap"

CURRENT_WALLPAPER=$XDG_CONFIG_HOME/current_wallpaper

wallpaper_file=""
keep_current=0
mapfile -t all_wallpapers < <(find "$DOTFILES/wallpapers" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | sort)

_usage() {
  cat <<\EOF
  Utility program to set the wallpaper. If no argument is provided a random wallpaper will be selected.

  Usage: set_wallpaper [options...] <wallpaper>
  -h, --help           - Shows this text
  -l, --list           - List available wallpapers
  -k, --keep-current   - Keep the current wallpaper
  -f, --file=<file>    - Use a specific file as wallpaper
EOF
}

_print_wallpapers() {
  echo "${all_wallpapers[@]}" | tr ' ' '\n' | awk -v cyan="$(tput setaf 6)" -v reset="$(tput sgr0)" '{print cyan $1 reset}'
}

_pick_fzf() {
  local selected_file preview_file
  selected_file="echo {} | awk '{print \$1}' | xargs -I {} find \"$DOTFILES/wallpapers\" -type f -name '{}*'"
  preview_file="${selected_file} | xargs -r fzf-preview"

  _print_wallpapers | fzf --preview "${preview_file}" --no-multi --ansi
}

_pick_wallpaper() {
  # If option 'keep-current' is enabled we keep the existing wallpaper. If the
  # existing wallpaper does not exist however, we use a default.
  if is_true "$keep_current"; then
    if [[ -L $CURRENT_WALLPAPER && -s $CURRENT_WALLPAPER ]]; then
      wallpaper_file=$(readlink -f "$CURRENT_WALLPAPER")
    else
      wallpaper_file=$DOTFILES/wallpapers/starry-night.jpg
    fi
    return 0
  fi

  # Pick from 'dotfiles/wallpapers' with fzf
  local new_wallpaper
  new_wallpaper=$(_pick_fzf)

  # If no wallpaper is picked, return 1
  [[ -z $new_wallpaper ]] && return 1

  wallpaper_file=$DOTFILES/wallpapers/$new_wallpaper
  return 0
}

_parse_args() {
  local i provided_wallpaper

  for i in "$@"; do
    case $i in
      -h|--help)
        _usage
        exit 0 ;;
      -l|--list)
        _print_wallpapers
        exit 0 ;;
      -k|--keep-current)
        keep_current=1
        shift ;;
      -f=*|--file=*)
        provided_wallpaper="${i#*=}"
        shift ;;
      -*) error "Unknown option: '$1'" ;;
      *) ;;
    esac
  done

  # Explicit file provided
  if [[ -n ${provided_wallpaper:-} ]]; then
    wallpaper_file="$(readlink -f "$provided_wallpaper" 2>/dev/null || echo "$provided_wallpaper")"
    keep_current=0
    return
  fi

  if [ $# -eq 0 ]; then
    _pick_wallpaper
  else
    wallpaper_file=$DOTFILES/wallpapers/$1
  fi
}

_set_wallpaper() {
  [[ ! -f $wallpaper_file ]] && error "Wallpaper '$wallpaper_file' not found, aborting!"

  ln -sf "$wallpaper_file" "$CURRENT_WALLPAPER"
  gsettings set org.gnome.desktop.background picture-uri "file:///$CURRENT_WALLPAPER"
  gsettings set org.gnome.desktop.background picture-options 'zoom'

  info "'$wallpaper_file' is your new wallpaper"
}

_parse_args "$@"
_set_wallpaper
