#!/usr/bin/env bash
# Set a theme.
#
# Examples:
#   dot-theme-set --list  # Print available themes
#   dot-theme-set NAME    # Provide a specific theme
#   dot-theme-set         # Pick the next available theme

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091

source "$DOTFILES/bootstrap"

mapfile -t ALL_THEMES < <(find "${DOTFILES}/themes" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

ARG="${1:-}"

if [ "${ARG}" = "--list" ]; then
  printf "%s\n" "${ALL_THEMES[@]}"
  exit
fi

if [ -z "${ARG}" ]; then
  ACTIVE_THEME_PATH="${XDG_CONFIG_HOME}/fzf/theme.sh"
  CURRENT_THEME=

  if [[ -L "${ACTIVE_THEME_PATH}" && -e "${ACTIVE_THEME_PATH}" ]]; then
    CURRENT_THEME=$(basename "$(dirname "$(readlink -f "${ACTIVE_THEME_PATH}")")")
  fi

  # Pick the first theme as a default.
  ARG="${ALL_THEMES[0]}"

  # Find the next theme, wrap back to the first one if at the end of the list.
  # Using ! ensures this returns an index (0, 1, etc.) instead of the name.
  for i in "${!ALL_THEMES[@]}"; do
    if [[ "${ALL_THEMES[${i}]}" = "${CURRENT_THEME}" ]]; then
      ARG="${ALL_THEMES[(i + 1) % ${#ALL_THEMES[@]}]}"
      break
    fi
  done
fi

_set_theme() {
  # Default to this theme as a fallback.
  local theme="tokyonight-moon"

  local active_theme=
  local theme_changed=
  local switch_wallpaper=1

  info "SETTING THEME"

  # Extract the theme name from the symlink path, ie. tokyonight-moon.
  # There are scenarios (first run, etc.) where this will be empty in which
  # case it being undefined is ok.
  if [ -f "${XDG_CONFIG_HOME}/fzf/theme.sh" ]; then
    active_theme="$(readlink "${XDG_CONFIG_HOME}/fzf/theme.sh")"
    active_theme="$(dirname "${active_theme}")"
    active_theme="$(basename "${active_theme##*/}")"
  fi

  theme="${1}"

  if [ ! -d "${DOTFILES}/themes/${theme}" ]; then
    echo "Theme '${theme}' not found, aborting!" >&2
    return 1
  fi

  # Did the theme change?
  [[ -n "${active_theme}" && "${active_theme}" != "${theme}" ]] && theme_changed=1

  mkdir -p \
    "${XDG_CONFIG_HOME}/btop/themes" \
    "${XDG_CONFIG_HOME}/fzf" \
    "${XDG_CONFIG_HOME}/ghostty" \
    "${XDG_CONFIG_HOME}/nvim/lua/plugins" \
    "${XDG_CONFIG_HOME}/tmux" \
    "${XDG_CONFIG_HOME}/wallpaper" \
    "${XDG_CONFIG_HOME}/mako" \
    "${XDG_CONFIG_HOME}/niri" \
    "${XDG_CONFIG_HOME}/swaylock" \
    "${XDG_CONFIG_HOME}/walker/themes/base" \
    "${XDG_CONFIG_HOME}/waybar" \
    "${XDG_CONFIG_HOME}/zathura" \
    "${XDG_CONFIG_HOME}/kitty" \
    "${XDG_CONFIG_HOME}/eza"

  ln -fns "${DOTFILES}/themes/${theme}/btop.theme" "${XDG_CONFIG_HOME}/btop/themes/theme.theme"
  ln -fns "${DOTFILES}/themes/${theme}/fzf.sh" "${XDG_CONFIG_HOME}/fzf/theme.sh"
  ln -fns "${DOTFILES}/themes/${theme}/ghostty" "${XDG_CONFIG_HOME}/ghostty/theme"
  ln -fns "${DOTFILES}/themes/${theme}/nvim.lua" "${XDG_CONFIG_HOME}/nvim/lua/plugins/theme.lua"
  ln -fns "${DOTFILES}/themes/${theme}/tmux.conf" "${XDG_CONFIG_HOME}/tmux/theme.conf"
  ln -fns "${DOTFILES}/themes/${theme}/eza.yml" "${XDG_CONFIG_HOME}/eza/theme.yaml"
  ln -fns "${DOTFILES}/themes/${theme}/kitty.conf" "${XDG_CONFIG_HOME}/kitty/theme.conf"

  ln -fns "${DOTFILES}/themes/${theme}/_theme.json" "${XDG_CONFIG_HOME}/wallpaper/theme.json"
  ln -fns "${DOTFILES}/themes/${theme}/mako" "${XDG_CONFIG_HOME}/mako/theme"
  ln -fns "${DOTFILES}/themes/${theme}/niri.kdl" "${XDG_CONFIG_HOME}/niri/theme.kdl"
  ln -fns "${DOTFILES}/themes/${theme}/swaylock" "${XDG_CONFIG_HOME}/swaylock/config"
  ln -fns "${DOTFILES}/themes/${theme}/walker.css" "${XDG_CONFIG_HOME}/walker/themes/base/theme.css"
  ln -fns "${DOTFILES}/themes/${theme}/waybar.css" "${XDG_CONFIG_HOME}/waybar/theme.css"
  ln -fns "${DOTFILES}/themes/${theme}/zathurarc" "${XDG_CONFIG_HOME}/zathura/themerc"

  local gtk_theme_path="${XDG_DATA_HOME}/themes/${theme}"

  if [ -d "${gtk_theme_path}" ]; then
    ln -fns "${gtk_theme_path}/gtk-4.0/assets" "${XDG_CONFIG_HOME}/gtk-4.0/assets"
    ln -fns "${gtk_theme_path}/gtk-4.0/gtk.css" "${XDG_CONFIG_HOME}/gtk-4.0/gtk.css"

    local gtk_theme_settings_path="${DOTFILES}/themes/${theme}/gtk.ini"

    if [ -f "${gtk_theme_settings_path}" ]; then
      ln -fns "${gtk_theme_settings_path}" "${XDG_CONFIG_HOME}/gtk-3.0/settings.ini"
      ln -fns "${gtk_theme_settings_path}" "${XDG_CONFIG_HOME}/gtk-4.0/settings.ini"
    fi

    # Load profile for gnome terminal
    dconf load /org/gnome/terminal/legacy/profiles:/ < ${DOTFILES}/themes/${theme}/gnome_terminal

    # This command works as a source of truth for GTK-3 and GTK-4 apps.
    # Given niri highly suggests installing xdg-desktop-portal-gnome, this
    # comes with glib2 which provides gsettings.
    #
    # Even after symlinking settings.ini, gsettings still needs to run to
    # switch the active theme so it takes effect.
    gsettings set org.gnome.desktop.interface gtk-theme "${theme}"

    # Change icon-theme
    gsettings set org.gnome.desktop.interface icon-theme "${theme}"
  fi

  [ -n "${switch_wallpaper}" ] && "${DOTFILES}/scripts/theme_set_bg"

  echo "'${theme}' is your active theme"
}

_set_theme "${ARG}"
